x-service-defaults: &service_defaults
  networks:
    - marcello
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "200k"
      max-file: "10"

services:
  saprouter:
    <<: *service_defaults
    container_name: saprouter
    ports:
      - "3299:3299"
    build:
      context: ./saprouter
      dockerfile: Dockerfile
    dns:
      - 192.168.42.3
      - 8.8.4.4
    volumes:
      - ./saprouter/saprouttab:/home/saprouter/saprouttab

networks:
  marcello:
